//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerRoleWithSBQueue1.GetNewCRMId {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Lebara.Backoffice.CRM.Service", ConfigurationName="GetNewCRMId.CRMService")]
    public interface CRMService {
        
        // CODEGEN: Generating message contract since the wrapper name (NewCRMIdRequest) of message NewCRMIdRequest does not match the default value (GenerateNewCRMId)
        [System.ServiceModel.OperationContractAttribute(Action="GenerateNewCRMId", ReplyAction="http://Lebara.Backoffice.CRM.Service/CRMService/GenerateNewCRMIdResponse")]
        WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdResponse GenerateNewCRMId(WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GenerateNewCRMId", ReplyAction="http://Lebara.Backoffice.CRM.Service/CRMService/GenerateNewCRMIdResponse")]
        System.Threading.Tasks.Task<WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdResponse> GenerateNewCRMIdAsync(WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewCRMIdRequest", WrapperNamespace="http://Lebara.Backoffice.CRM.Service", IsWrapped=true)]
    public partial class NewCRMIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Lebara.Backoffice.CRM.Service", Order=0)]
        public System.DateTime Stamp;
        
        public NewCRMIdRequest() {
        }
        
        public NewCRMIdRequest(System.DateTime Stamp) {
            this.Stamp = Stamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewCRMIdResponse", WrapperNamespace="http://Lebara.Backoffice.CRM.Service", IsWrapped=true)]
    public partial class NewCRMIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Lebara.Backoffice.CRM.Service", Order=0)]
        public string NewCRMId;
        
        public NewCRMIdResponse() {
        }
        
        public NewCRMIdResponse(string NewCRMId) {
            this.NewCRMId = NewCRMId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRMServiceChannel : WorkerRoleWithSBQueue1.GetNewCRMId.CRMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRMServiceClient : System.ServiceModel.ClientBase<WorkerRoleWithSBQueue1.GetNewCRMId.CRMService>, WorkerRoleWithSBQueue1.GetNewCRMId.CRMService {
        
        public CRMServiceClient() {
        }
        
        public CRMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdResponse WorkerRoleWithSBQueue1.GetNewCRMId.CRMService.GenerateNewCRMId(WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest request) {
            return base.Channel.GenerateNewCRMId(request);
        }
        
        public string GenerateNewCRMId(System.DateTime Stamp) {
            WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest inValue = new WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest();
            inValue.Stamp = Stamp;
            WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdResponse retVal = ((WorkerRoleWithSBQueue1.GetNewCRMId.CRMService)(this)).GenerateNewCRMId(inValue);
            return retVal.NewCRMId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdResponse> WorkerRoleWithSBQueue1.GetNewCRMId.CRMService.GenerateNewCRMIdAsync(WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest request) {
            return base.Channel.GenerateNewCRMIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdResponse> GenerateNewCRMIdAsync(System.DateTime Stamp) {
            WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest inValue = new WorkerRoleWithSBQueue1.GetNewCRMId.NewCRMIdRequest();
            inValue.Stamp = Stamp;
            return ((WorkerRoleWithSBQueue1.GetNewCRMId.CRMService)(this)).GenerateNewCRMIdAsync(inValue);
        }
    }
}
